-- D1 schema for cf-shortlink
CREATE TABLE IF NOT EXISTS links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT NOT NULL UNIQUE,
  target_url TEXT NOT NULL,
  note TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  is_deleted INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER IF NOT EXISTS trigger_links_updated_at
AFTER UPDATE ON links
FOR EACH ROW
BEGIN
  UPDATE links SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
